version: '3'

services:
  api:
    build:
      context: api
      dockerfile: development.Dockerfile
    environment:
      - VIRTUAL_HOST=app-local.arm.ag/api,app-local.arm.ag/api/*
      - VIRTUAL_HOST_WEIGHT=1
      - DB_URL=mongodb://mongodb/wtm
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
      dockerfile: development.Dockerfile
    environment:
      - HOST=0.0.0.0
      - VIRTUAL_HOST=app-local.arm.ag
      - APP_ENV=development
    volumes:
      - ./frontend/config:/app/config
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
    expose:
      - 8080

  mongodb:
    image: mongo:latest

  load-balancer:
    image: dockercloud/haproxy
    links:
      - api
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure
